CREATE DATABASE EventMoura;
GO

USE EventMoura;
GO

CREATE TABLE TipoEvento (
    IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE TipoUsuario (
    IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Instituicao (
    IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(150) NOT NULL,
    NomeFantasia VARCHAR(150),
    Endereco VARCHAR(200)
);

CREATE TABLE Usuario (
    IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(150) NOT NULL,
    Email VARCHAR(150) NOT NULL,
    Senha VARCHAR(200) NOT NULL,
    IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario
    (IdTipoUsuario)    
);
GO

CREATE TABLE Evento (
    IdEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome NVARCHAR(150) NOT NULL,
    Descricao TEXT NOT NULL,
    DataEvento DATETIME NOT NULL,
    IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento
    (IdTipoEvento),
    IdInstituicao UNIQUEIDENTIFIER FOREIgn KEY REFERENCES Instituicao
    (IdInstituicao)
);
GO

CREATE TABLE Presenca (
    IdPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Situacao BIT NOT NULL,
    IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento),
    IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
);

CREATE TABLE ComentarioEvento (
    IdComentario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Descricao VARCHAR(300),
    DataComentarioEvento DATETIME NOT NULL,
    Exibi BIT NOT NULL,
    IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento),
    IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)
);