CREATE DATABASE FilmesBD_Moura1;
GO

USE FilmesBD_Moura1;
GO

CREATE TABLE Genero(
	IdGenero VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Filme(
	IdFilme VARCHAR(40) PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL,
	Imagem VARCHAR(100),
	IdGenereo VARCHAR(40) FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO

CREATE TABLE Usuario(
	IdUsuario VARCHAR(40) PRIMARY KEY,
	Senha VARCHAR(60) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL
);
GO

SELECT * FROM Genero;
