CREATE DATABASE EventBD;

USE EventBD;

CREATE TABLE TipoUsuario(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(20) NOT NULL
);

CREATE TABLE Usuario(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	Senha NVARCHAR(60) NOT NULL,
	Email NVARCHAR(256) NOT NULL UNIQUE,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)
	
);

CREATE TABLE Instituicao(
	IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	NomeFantasia NVARCHAR(150) NOT NULL,
	CNPJ CHAR(14) NOT NULL UNIQUE, -- CHAR pq cnpj tem um numero fixo
	Endereco NVARCHAR(200) NOT NULL
);

CREATE TABLE TipoEvento(
	IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(20) NOT NULL
);

CREATE TABLE Evento(
	IdEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	DataEvento DATETIME NOT NULL,
	Descricao TEXT NOT NULL,
	IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento(IdTipoEvento),
	IdInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IdInstituicao)

);

CREATE TABLE ComentarioEvento(
	IdComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Exibe BIT NOT NULL,
	DataComentarioEvento DATETIME NOT NULL,
	Descricao NVARCHAR(200) NOT NULL,
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)
);

CREATE TABLE Presenca(
	IdPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Situacao BIT NOT NULL,
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)

);

SELECT * FROM TipoUsuario;
SELECT * FROM Instituicao;
SELECT * FROM TipoEvento;
SELECT * FROM ComentarioEvento;
SELECT * FROM Presenca;

SELECT * FROM Usuario;
SELECT * FROM Evento;